### ISSUE TITLE
weird crash n°1

### ISSUE THREAD

**Issue by sonicolasj** [tcwatson/SquadTracker#26]
Source: https://discord.com/channels/531175899588984842/534492173362528287/950160623856152667

```text
[11:39 PM] TheHermit: Crash after enabling the SquadTracker module

Blish HUD v0.11.7+Branch.tags-v0.11.7.Sha.0c709c76cb502d310f2964dca92ce770e533dae2
17:10:55.8692 | INFO  | Blish_HUD.Program | Running Build "Branch.tags-v0.11.7.Sha.0c709c76cb502d310f2964dca92ce770e533dae2"
17:10:55.8692 | INFO  | Blish_HUD.Program | Launched from "C:\Program Files\Guild Wars 2\Blish HUD" with args "".
17:10:57.7797 | INFO  | Blish_HUD.Contexts.FestivalContext | Active festival(s): ""
17:10:57.7797 | INFO  | Blish_HUD.Modules.Pkgs.StaticPkgRepoProvider | Getting module list...
17:11:10.8013 | INFO  | BhModule.Community.ErrorSubmissionModule.ErrorSubmissionModule | Sentry hook enabled.
17:11:10.8693 | INFO  | BhModule.Community.ErrorSubmissionModule.ErrorSubmissionModule | etm.sdk context registered.
17:11:10.8693 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "markers" ("C:\Users\<redacted>\OneDrive\Documents\Guild Wars 2\addons\blishhud\markers") was registered.
17:11:11.2139 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "timers" ("C:\Users\<redacted>\OneDrive\Documents\Guild Wars 2\addons\blishhud\timers") was registered.
17:11:11.4349 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "hpgrid" ("C:\Users\<redacted>\OneDrive\Documents\Guild Wars 2\addons\blishhud\hpgrid") was registered.
17:11:11.4719 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "mousecursor" ("C:\Users\<redacted>\OneDrive\Documents\Guild Wars 2\addons\blishhud\mousecursor") was registered.
17:11:11.6105 | INFO  | Blish_HUD.Modules.Module | Module "Error Submission Module (bh.community.etm) v3.0.0" finished loading.
17:11:11.6105 | INFO  | Blish_HUD.Modules.Module | Module "Discord Rich Presence (bh.general.discordrp) v0.3.5" finished loading.
17:11:11.6105 | INFO  | Blish_HUD.Modules.Module | Module "HP Grids (Manlaan.HPGrid) v1.0.4" finished loading.
17:11:11.6205 | INFO  | Blish_HUD.Modules.Module | Module "Mouse Cursor (Manlaan.MouseCursor) v2.2.0" finished loading.
17:11:11.6205 | INFO  | Blish_HUD.Modules.Module | Module "Regions of Tyria (Nekres.Regions_Of_Tyria) v0.5.5" finished loading.
17:11:11.9020 | INFO  | Blish_HUD.Gw2WebApiService | Associated API key "The Hermit.3542" with characters: "Baron Von Fur, Cland Estine, Thehermit, Fluffy Von Bubbles, Vyx Tinyshadow, Zapz Branigan, Raine Verdance, Olaffina Jormungar, Hermie Winkle, Zapz Brannigan, Rings And Things, Witty Revenant Pun, Cherry Sieran"
17:11:12.1871 | INFO  | Blish_HUD.Modules.Module | Module "Pathing (bh.community.pathing) v0.17.5" finished loading.
17:11:13.3058 | INFO  | Blish_HUD.Modules.Module | Module "Timers (Charr.Timers_BlishHUD) v0.3.7" finished loading.
17:11:13.9869 | INFO  | Blish_HUD.Modules.Module | Module "Kill Proof Module (KillProofModule) v1.7.8" finished loading.
17:11:14.8792 | INFO  | Events_Module.Meta | Loaded 51 events.
17:11:15.1658 | INFO  | Blish_HUD.Modules.Module | Module "Events and Metas Observer (bh.general.events) v0.9.1" finished loading.
17:11:18.1894 | INFO  | Blish_HUD.GameIntegration.ClientTypeIntegration | Detected Guild Wars 2 client to be the Standard version.
17:11:20.2157 | INFO  | BhModule.Community.Pathing.PackInitiator | Finished loading packs Hero.Blish.Pack, GW2 TacO ReActif EN External, tt.hptraintrails, tt.mapcomp, tw_ALL_IN_ONE, markers in 1987 ms for map 1428.
17:14:59.6439 | INFO  | BhModule.Community.Pathing.PackInitiator | Finished loading packs Hero.Blish.Pack, GW2 TacO ReActif EN External, tt.hptraintrails, tt.mapcomp, tw_ALL_IN_ONE, markers in 1737 ms for map 1452.
17:15:31.6217 | INFO  | BhModule.Community.Pathing.PackInitiator | Finished loading packs Hero.Blish.Pack, GW2 TacO ReActif EN External, tt.hptraintrails, tt.mapcomp, tw_ALL_IN_ONE, markers in 1776 ms for map 1428.
17:18:09.9838 | INFO  | BhModule.Community.Pathing.PackInitiator | Finished loading packs Hero.Blish.Pack, GW2 TacO ReActif EN External, tt.hptraintrails, tt.mapcomp, tw_ALL_IN_ONE, markers in 2339 ms for map 1206.
17:23:47.1401 | INFO  | BhModule.Community.Pathing.PackInitiator | Finished loading packs Hero.Blish.Pack, GW2 TacO ReActif EN External, tt.hptraintrails, tt.mapcomp, tw_ALL_IN_ONE, markers in 1751 ms for map 1452.
17:24:07.3017 | INFO  | BhModule.Community.Pathing.PackInitiator | Finished loading packs Hero.Blish.Pack, GW2 TacO ReActif EN External, tt.hptraintrails, tt.mapcomp, tw_ALL_IN_ONE, markers in 1785 ms for map 1428.
17:26:42.2661 | INFO  | BhModule.Community.Pathing.PackInitiator | Finished loading packs Hero.Blish.Pack, GW2 TacO ReActif EN External, tt.hptraintrails, tt.mapcomp, tw_ALL_IN_ONE, markers in 1904 ms for map 1452.
17:31:48.4581 | INFO  | Blish_HUD.Modules.ModulePkgRepoHandler | Torlando.SquadTracker_0.1.1.bhm matched expected checksum '1AF595E89FB242D01089789B0FCF226423AA12A55A8483A176887C4B4A99408A'.
17:31:48.4581 | INFO  | Blish_HUD.Modules.ModulePkgRepoHandler | Module saved to 'C:\Users\<redacted>\OneDrive\Documents\Guild Wars 2\addons\blishhud\modules\Torlando.SquadTracker_0.1.1.bhm'.
17:31:56.0464 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "squadtracker" ("C:\Users\<redacted>\OneDrive\Documents\Guild Wars 2\addons\blishhud\squadtracker") was registered.
17:31:56.3690 | INFO  | Blish_HUD.Modules.Module | Module "Squad Tracker (Torlando.SquadTracker) v0.1.1" finished loading.
17:35:59.2444 | FATAL | Blish_HUD.DebugService | Blish HUD encountered a fatal crash!
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Torlando.SquadTracker.Module.PlayerRemovedEvent(Player player) in C:\Users\<redacted>\source\repos\SquadTracker\Module.cs:line 189
   at Blish_HUD.ArcDps.Common.CommonFields.PresentPlayersChange.Invoke(Player player)
   at Blish_HUD.ArcDps.Common.CommonFields.CombatHandler(Object sender, RawCombatEventArgs args) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\ArcDps\Common\CommonFields.cs:line 67
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Blish_HUD.ArcDps.SocketListener.ProcessReceivedData(Int32 dataStartOffset, Int32 totalReceivedDataSize, Int32 alreadyProcessedDataSize, AsyncUserToken token, Byte[] buffer) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\ArcDps\SocketListener\SocketListener.cs:line 170
   at Blish_HUD.ArcDps.SocketListener.ProcessReceive(SocketAsyncEventArgs e) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\ArcDps\SocketListener\SocketListener.cs:line 102
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

[11:40 PM] TheHermit: I created a squad then joined one in LFG, but I'm unsure if that's the exact moment it crashed 
```

**Comment by sonicolasj** [comment]
Related code: https://github.com/tcwatson/SquadTracker/blob/dfd0e5e71ad5593911f760f7e935d6a6620f4c4a/PlayerCollection.cs#L98
